[package]
name = "pos"
version = "0.1.0"
edition = "2021"


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace]
members = ["simple_boot"]

[dependencies]
bootloader = "0.10.12"
